name: objectbox_generator
description: ObjectBox Flutter / Dart database binding code generator - finds annotated entities and adds them to the ObjectBox DB model.
# Link to actual directory in repository so file links on pub.dev work.
repository: https://github.com/objectbox/objectbox-dart/tree/main/generator
homepage: https://objectbox.io
version: 6.0.0-beta

environment:
  sdk: ^3.7.0 # 3.7 has new dart format rules

dependencies:
  objectbox: 6.0.0-beta
  # https://pub.dev/packages/analyzer/changelog
  analyzer: '>=8.1.1 <15.0.0'
  # https://pub.dev/packages/build/changelog
  build: ^4.0.6
  # https://pub.dev/packages/collection/changelog
  collection: ^1.19.1
  dart_style: ^3.1.2
  glob: ^2.2.0
  path: ^1.9.1
  # https://pub.dev/packages/source_gen/changelog
  source_gen: ^4.2.0
  pubspec_parse: ^1.5.0
  yaml: ^3.1.4
  http: ^1.6.0
  pointycastle: ^4.0.0

dev_dependencies:
  test: ^1.31.0 # 1.31.1 requires Dart 3.10, but still testing with 3.7
  lints: ">=5.1.1 <7.0.0" # 6.0.0 requires Dart 3.8, but still testing with 3.7
  pub_semver: ^2.2.1
  # https://pub.dev/packages/build_test/changelog
  build_test: ^3.5.15 # 3.5.16 requires Dart 3.8, but still testing with 3.7
  logging: ^1.3.0
