name: objectbox
description: Flutter database for super-fast NoSQL ACID compliant object persistence.
homepage: https://objectbox.io
# Link to actual directory in repository so file links on pub.dev work.
repository: https://github.com/objectbox/objectbox-dart/tree/main/objectbox
documentation: https://docs.objectbox.io
version: 6.0.0-beta

environment:
  # minimum Dart SDK (also see generator and flutter_libs)
  sdk: ^3.7.0 # 3.7 has new dart format rules

dependencies:
  collection: ^1.19.1
  # take care updating flatbuffers - keep aligned with other bindings
  flat_buffers: 25.9.23
  ffi: ^2.2.0
  # Allow 1.18.0 because lowest supported Flutter 3.44 has it pinned
  # https://dart.dev/go/sdk-version-pinning
  meta: ^1.18.0
  path: ^1.9.1

dev_dependencies:
  ffigen: ^22.0.0 # Requires Dart 3.10, but only used to regenerate bindings.
  lints: ^6.1.0
  test: ^1.32.0 # To run coverage on this package.

# The ffigen configuration was migrated to the FfiGenerator Dart API,
# see tool/ffigen.dart.
