name: vectorsearch_cities
description: Vector Search Example with Cities.
version: 1.0.0

environment:
  sdk: ^3.12.1

dependencies:
  objectbox: ^6.0.0-preview.2

dev_dependencies:
  build_runner: ^2.15.0
  lints: ^6.1.0
  objectbox_generator: any

# Note: these overrides are only for ObjectBox internal development, don't use them in your app.
dependency_overrides:
  objectbox:
    path: ../../../../objectbox
  objectbox_generator:
    path: ../../../../generator
