name: objectbox_generator_test

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  objectbox: any

dev_dependencies:
  objectbox_generator: any
  test: any
  build_runner: any
  build_test: any
  io: any
  path: any

dependency_overrides:
  objectbox:
    path: ../../../objectbox
  objectbox_generator:
    path: ../../